import type { Metadata } from "next";
import { Gabarito, Courgette, Pacifico } from "next/font/google";
import "./globals.css";
import RootLayoutWrapper from "./components/RootLayoutWrapper";
import { AuthProvider } from './context/AuthContext';
import { CartProvider } from './context/CartContext';
import CookieConsent from './components/CookieConsent';

const gabarito = Gabarito({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: '--font-gabarito',
});

const courgette = Courgette({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-courgette",
});

const pacifico = Pacifico({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-pacifico",
});

export const metadata: Metadata = {
  title: "Bloemigeverleiding",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${gabarito.variable} ${courgette.variable} ${pacifico.variable} font-sans antialiased min-h-screen flex flex-col pt-20`}>
        <AuthProvider>
          <CartProvider>
            <RootLayoutWrapper>
              {children}
            </RootLayoutWrapper>
          </CartProvider>
        </AuthProvider>
        <CookieConsent />
      </body>
    </html>
  );
}
